import requests
from datetime import datetime

class SlackNotifier:
    """Send alerts to Slack via webhook"""
    
    def __init__(self, webhook_url, config=None):
        """
        Initialize Slack notifier
        
        Args:
            webhook_url: Slack webhook URL
            config: Alert configuration
        """
        self.webhook_url = webhook_url
        self.config = config or {
            'triggers': {
                'cost_spike_threshold': 30,
                'high_savings_threshold': 500,
                'critical_issues': True
            },
            'send_summary': True,
            'send_details': True,
            'mention_channel': False
        }
    
    def send_cost_spike_alert(self, spike_data):
        """
        Send alert for cost spike
        
        Args:
            spike_data: Dict with spike information
        """
        percentage = spike_data.get('percentage', 0)
        current_cost = spike_data.get('current_cost', 0)
        previous_cost = spike_data.get('previous_cost', 0)
        date = spike_data.get('date', datetime.now().strftime('%Y-%m-%d'))
        
        message = {
            "blocks": [
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": "🚨 AWS Cost Spike Detected!",
                        "emoji": True
                    }
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": f"*Date:*\n{date}"
                        },
                        {
                            "type": "mrkdwn",
                            "text": f"*Increase:*\n{percentage:.1f}%"
                        },
                        {
                            "type": "mrkdwn",
                            "text": f"*Previous:*\n${previous_cost:.2f}"
                        },
                        {
                            "type": "mrkdwn",
                            "text": f"*Current:*\n${current_cost:.2f}"
                        }
                    ]
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"⚠️ Daily AWS cost increased by *{percentage:.1f}%* (${current_cost - previous_cost:.2f})"
                    }
                },
                {
                    "type": "context",
                    "elements": [
                        {
                            "type": "mrkdwn",
                            "text": f"Generated by AWS Cost Analyzer | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
                        }
                    ]
                }
            ]
        }
        
        if self.config.get('mention_channel'):
            message['text'] = "<!channel> AWS Cost Spike Detected!"
        
        return self._send_message(message)
    
    def send_high_savings_alert(self, savings_data):
        """
        Send alert for high potential savings
        
        Args:
            savings_data: Dict with savings information
        """
        monthly_savings = savings_data.get('monthly_savings', 0)
        yearly_savings = savings_data.get('yearly_savings', 0)
        issue_count = savings_data.get('total_issues', 0)
        top_issues = savings_data.get('top_issues', [])
        
        # Build issue list
        issue_text = "\n".join([
            f"• {issue['type']}: ${issue['savings']:.2f}/month"
            for issue in top_issues[:5]
        ])
        
        message = {
            "blocks": [
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": "💰 High Cost Savings Opportunity!",
                        "emoji": True
                    }
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": f"*Monthly Savings:*\n${monthly_savings:.2f}"
                        },
                        {
                            "type": "mrkdwn",
                            "text": f"*Yearly Savings:*\n${yearly_savings:.2f}"
                        },
                        {
                            "type": "mrkdwn",
                            "text": f"*Issues Found:*\n{issue_count}"
                        },
                        {
                            "type": "mrkdwn",
                            "text": f"*Severity:*\nHIGH"
                        }
                    ]
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"*Top Issues:*\n{issue_text}"
                    }
                },
                {
                    "type": "context",
                    "elements": [
                        {
                            "type": "mrkdwn",
                            "text": "💡 Review full report for detailed recommendations"
                        }
                    ]
                }
            ]
        }
        
        return self._send_message(message)
    
    def send_summary_report(self, analysis_data):
        """
        Send summary analysis report
        
        Args:
            analysis_data: Complete analysis results
        """
        total_savings = analysis_data.get('total_savings', {})
        issue_summary = analysis_data.get('issue_summary', {})
        
        message = {
            "blocks": [
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": "📊 AWS Cost Analysis Complete",
                        "emoji": True
                    }
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": f"*Total Issues:*\n{analysis_data.get('total_issues', 0)}"
                        },
                        {
                            "type": "mrkdwn",
                            "text": f"*Monthly Savings:*\n${total_savings.get('monthly_savings', 0):.2f}"
                        }
                    ]
                },
                {
                    "type": "divider"
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": "*Issue Breakdown:*\n" + "\n".join([
                            f"• {issue_type}: {count} found"
                            for issue_type, count in issue_summary.items()
                        ])
                    }
                },
                {
                    "type": "context",
                    "elements": [
                        {
                            "type": "mrkdwn",
                            "text": f"Report generated at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
                        }
                    ]
                }
            ]
        }
        
        return self._send_message(message)
    
    def _send_message(self, message):
        """Send message to Slack"""
        try:
            response = requests.post(
                self.webhook_url,
                json=message,
                timeout=10
            )
            
            if response.status_code == 200:
                return {'success': True, 'message': 'Alert sent to Slack'}
            else:
                return {
                    'success': False,
                    'error': f'Slack API error: {response.status_code}'
                }
        
        except requests.exceptions.RequestException as e:
            return {
                'success': False,
                'error': f'Failed to send Slack alert: {str(e)}'
            }
    
    def test_connection(self):
        """Test Slack webhook connection"""
        message = {
            "blocks": [
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": "✅ AWS Cost Analyzer connected successfully!"
                    }
                }
            ]
        }
        return self._send_message(message)